# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Build KernelSU-Next

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build ${{ matrix.variant.name }} Kernel${{ matrix.variant.ksu_add_susfs && ' (with  SuSFS)' || '' }}
    runs-on: [ubuntu-latest, campus]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        toolchains_url:
          - https://openlist.campus.lk233.link/d/samsung_dev/toolchains/s24_toolchain.tar.gz
        src_urls:
          - boot_img_url: https://openlist.campus.lk233.link/d/samsung_dev/s24/6.1.99_S9210ZHU4BYD9/boot.img
            kernel_source_url: https://openlist.campus.lk233.link/d/samsung_dev/s24/6.1.99_S9210ZHU4BYD9/SM-S9210_HKTW_15_Opensource.zip
        variant:
          - config_file: build.ksunext.config
            name: KernelSU-Next
            ksu_add_susfs: true
            branch: next-susfs
          - config_file: build.ksunext.config
            name: KernelSU-Next
            ksu_add_susfs: false
            branch: next
          - config_file: build.sukisuu.config
            name: SukiSU Ultra
            ksu_add_susfs: true
            branch: susfs-main
          - config_file: build.sukisuu.config
            name: SukiSU Ultra
            ksu_add_susfs: false
            branch: main
    env:
      CONFIG_FILE: ${{ matrix.variant.config_file }}
      KERNEL_BOOT_IMG_URL: ${{ matrix.src_urls.boot_img_url }}
      KERNEL_SOURCE_URL: ${{ matrix.src_urls.kernel_source_url }}
      TOOLCHAINS_URL: ${{ matrix.toolchains_url }}
      cache_root: ${{ github.workspace }}/.cache
      ksu_add_susfs: ${{ matrix.variant.ksu_add_susfs }}
      ksu_branch: ${{ matrix.variant.branch }}
    steps:
      - name: Print Environment
        run: |
          echo "export CONFIG_FILE=$CONFIG_FILE"
          echo "export KERNEL_BOOT_IMG_URL=$KERNEL_BOOT_IMG_URL"
          echo "export KERNEL_SOURCE_URL=$KERNEL_SOURCE_URL"
          echo "export TOOLCHAINS_URL=$TOOLCHAINS_URL"
          echo "export cache_root=$cache_root"

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.cache_root }}
          key: |
            build-kernel-${{ hashFiles(matrix.variant.config_file) }}
          restore-keys: |
            build-kernel-
      - name: Install Docker Dependencies
        run: |
          sed -i 's@//.*archive.ubuntu.com@//mirrors.nju.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources
          apt-get update
          apt-get install -y fuse-overlayfs apt-utils nftables
          fuse-overlayfs -V

      - name: Set up Docker
        uses: https://github.com/LazuliKao/setup-docker-action@v4.6.0
        with:
          docker-mirror: https://mirrors.zju.edu.cn/docker-ce
          version: "29.1.1"
          set-host: true
          daemon-config: | #json
            {
              "storage-driver": "fuse-overlayfs",
              "firewall-backend": "nftables"
            }

      - name: Setup build config
        run: |
          cat $CONFIG_FILE

      - name: Prepare kernel source
        run: |
          chmod +x build.sh
          chmod +x scripts/*.sh
          ./build.sh prepare

      - name: Build kernel
        id: build
        run: |
          ./build.sh kernel

          # Print release info for logging
          INFO_JSON="kernel_edit/build/dist/release_info.json"
          if [ -f "$INFO_JSON" ]; then
            echo "Release info:"
            cat $INFO_JSON | jq .
          fi

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-ksunext-${{ github.sha }}
          path: |
            kernel_edit/build/dist/*
          if-no-files-found: error
          retention-days: 30

      - name: Release
        uses: https://github.com/LazuliKao/action-gh-release@v2.5.0
        with:
          name: ${{ steps.build.outputs.release_name }}-${{ matrix.variant.name }}
          tag_name: v${{ steps.build.outputs.release_tag }}-${{ matrix.variant.name }}
          prerelease: true
          repository: LazuliKao/android_kernel_samsung_sm8650
          body: |
            ## Kernel Build Information

            | Component | Version |
            |-----------|----------|
            | **Kernel Version** | ${{ steps.build.outputs.kernel_version }} |
            | **KernelSU Type** | ${{ steps.build.outputs.ksu_type_name }} |
            | **KernelSU Version** | ${{ steps.build.outputs.ksu_version }} |
            | **KernelSU Branch** | ${{ steps.build.outputs.ksu_branch }} |
            ${{ steps.build.outputs.susfs_enabled == 'true' && format('| **SUSFS Version** | {0} |', steps.build.outputs.susfs_version) || '' }}
            ${{ steps.build.outputs.susfs_enabled == 'true' && format('| **SUSFS Branch** | {0} |', steps.build.outputs.susfs_branch) || '' }}

            ## Build Details

            - **Build Date**: ${{ steps.build.outputs.build_date }}
            - **Architecture**: arm64
            - **Local Version**: ${{ steps.build.outputs.local_version || 'N/A' }}
            - **Variant**: ${{ matrix.variant.name }}
            - **Commit**: ${{ github.sha }}
            - **Branch**: ${{ github.ref_name }}

            ## Files Included

            - `AnyKernel.zip` - Flashable zip for custom recovery
            - `boot.img` - Flashable boot image (if available)
            - `kernel` - Raw kernel image

            ## Installation

            ### Using AnyKernel (Recommended)
            1. Boot into custom recovery (TWRP/OrangeFox)
            2. Flash `AnyKernel.zip`
            3. Reboot

            ### Using boot.img
            1. Use Odin or fastboot to flash `boot.img` to boot partition
            2. Reboot

          files: kernel_edit/build/dist/*
          fail_on_unmatched_files: true

          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          github_api_url: https://api.github.com

      - name: Collect patch failure files
        if: failure()
        run: |
          mkdir -p patch_failures
          # Find all .rej files and copy them with directory structure
          find kernel_edit -name "*.rej" -type f | while read rej_file; do
            # Create target directory
            target_dir="patch_failures/$(dirname "$rej_file")"
            mkdir -p "$target_dir"
            cp "$rej_file" "$target_dir/"
            
            # Copy corresponding original file (without .rej extension)
            orig_file="${rej_file%.rej}"
            if [ -f "$orig_file" ]; then
              cp "$orig_file" "$target_dir/"
            fi
            
            # Copy .orig file if exists
            orig_backup="${orig_file}.orig"
            if [ -f "$orig_backup" ]; then
              cp "$orig_backup" "$target_dir/"
            fi
          done

          # List collected files
          echo "Collected patch failure files:"
          find patch_failures -type f | head -100

          # Initialize git in patch_failures for generating patches
          cd patch_failures/kernel_edit
          git init
          git config user.email "ci@build.local"
          git config user.name "CI Build"
          git add -A
          git commit -m "Initial patch failure files state"
          echo "Git repository initialized in patch_failures"

      - name: Upload patch failure artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: patch-failures-${{ matrix.variant.name }}-${{ github.sha }}
          path: patch_failures/kernel_edit
          if-no-files-found: ignore
          retention-days: 7
          include-hidden-files: true

      - name: Debug with Upterm
        if: failure()
        uses: https://github.com/LazuliKao/action-upterm@v1.11.1
        with:
          upterm-server: ssh://upterm.home.lk233.link:2222
          wait-timeout-minutes: 30
          authorized-keys: ${{ secrets.UPTERM_AUTHORIZED_KEYS }}
