name: Build SukiSU-Ultra

on:
  push:
    branches:
      - main
      - master
    paths:
      - "build.sukisuu.config"
      - "build.sh"
      - "scripts/**"
      - "kernel_patches/**"
      - ".forgejo/workflows/build-sukisuu.yml"
      - ".forgejo/workflows/build-kernel.yml"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-sukisuu:
    uses: ./.forgejo/workflows/build-kernel.yml
    with:
      config_file: build.sukisuu.config
      variant_name: sukisuu

  release:
    name: Create Release
    runs-on: [home, docker]
    needs: [build-sukisuu]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: kernel-sukisuu-${{ github.sha }}
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.img
            artifacts/**/*.zip
          generate_release_notes: true
          draft: false
          prerelease: false
