name: Build KernelSU-Next (Test)

on:
  workflow_call:
      inputs:
        config_file:
          description: 'Build config file to use'
          required: true
          type: string
        variant_name:
          description: 'Variant name for artifacts'
          required: true
          type: string
        boot_img_url:
          description: 'Kernel boot image URL'
          required: false
          type: string
        kernel_source_url:
          description: 'Kernel source URL'
          required: false
          type: string
        toolchains_url:
          description: 'Toolchains URL'
          required: false
          type: string
jobs:
  build:
    name: Build ksunext
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: ${{ inputs.config_file }}
      KERNEL_BOOT_IMG_URL: ${{ inputs.boot_img_url }}
      KERNEL_SOURCE_URL: ${{ inputs.kernel_source_url }}
      TOOLCHAINS_URL: ${{ inputs.toolchains_url }}
      cache_root: ${{ github.workspace }}/.cache
    steps:
      - name: Print Config
        run: |
          echo "CONFIG_FILE=$CONFIG_FILE"
          echo "KERNEL_BOOT_IMG_URL=$KERNEL_BOOT_IMG_URL"
          echo "KERNEL_SOURCE_URL=$KERNEL_SOURCE_URL"
          echo "TOOLCHAINS_URL=$TOOLCHAINS_URL"
          echo "cache_root=$cache_root"
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.cache_root }}
          key: ${{ runner.os }}-ksunext-${{ hashFiles('build.ksunext.config') }}
          restore-keys: |
            ${{ runner.os }}-ksunext-
      - name: Install Docker
        run: |
          sed -i 's@//.*archive.ubuntu.com@//mirrors.nju.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources
          apt-get update
          apt-get install -y fuse-overlayfs apt-utils nftables
          fuse-overlayfs -V

      - name: Set up Docker
        uses: https://github.com/docker/setup-docker-action@v4
        with:
          set-host: true
          daemon-config: | #json
            {
              "storage-driver": "fuse-overlayfs",
              "firewall-backend": "nftables"
            }

      - name: Setup build config
        run: |
          cat $CONFIG_FILE

      - name: Prepare kernel source
        run: |
          chmod +x build.sh
          chmod +x scripts/*.sh
          ./build.sh prepare

      - name: Build kernel
        id: build
        run: |
          ./build.sh kernel

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v5
        with:
          name: kernel-ksunext-${{ github.sha }}
          path: |
            kernel_edit/build/dist/*
          if-no-files-found: error
          retention-days: 30

      - uses: actions/checkout@v2
      - name: Debug with Upterm
        if: failure()
        uses: https://github.com/owenthereal/action-upterm@v1
        with:
          upterm-server: wss://upterm.home.lk233.link:8443
          wait-timeout-minutes: 30
