name: Build KernelSU-Next (Test)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ksunext
    runs-on: [campus, docker, ubuntu-latest]

    env:
      CONFIG_FILE: build.sukisuu.config
      KERNEL_BOOT_IMG_URL: https://openlist.campus.lk233.link/d/samsung_dev/s24/6.1.99_S9210ZHU4BYD9/boot.img
      KERNEL_SOURCE_URL: https://openlist.campus.lk233.link/d/samsung_dev/s24/6.1.99_S9210ZHU4BYD9/SM-S9210_HKTW_15_Opensource.zip
      TOOLCHAINS_URL: https://openlist.campus.lk233.link/d/samsung_dev/toolchains/s24_toolchain.tar.gz
      cache_root: ${{ github.workspace }}/.cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.cache_root }}
          key: ${{ runner.os }}-ksunext-${{ hashFiles('build.ksunext.config') }}
          restore-keys: |
            ${{ runner.os }}-ksunext-
      - name: Install Docker
        run: |
          sed -i 's@//.*archive.ubuntu.com@//mirrors.nju.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources
          apt-get update
          apt-get install -y fuse-overlayfs apt-utils nftables
          fuse-overlayfs -V

      - name: Set up Docker
        uses: https://github.com/docker/setup-docker-action@v4
        with:
          set-host: true
          daemon-config: |
            {
              "storage-driver": "fuse-overlayfs",
              "firewall-backend": "nftables"
            }

      - name: Setup build config
        run: |
          cat $CONFIG_FILE

      - name: Prepare kernel source
        run: |
          chmod +x build.sh
          chmod +x scripts/*.sh
          ./build.sh prepare

      - name: Build kernel
        id: build
        run: |
          ./build.sh kernel

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v5
        with:
          name: kernel-ksunext-${{ github.sha }}
          path: |
            kernel_source_*/out/**/*.img
            kernel_source_*/out/**/*.zip
          if-no-files-found: warn
          retention-days: 30

      - uses: actions/checkout@v2
      - name: Debug with Upterm
        if: failure()
        uses: https://github.com/owenthereal/action-upterm@v1
        with:
          upterm-server: wss://upterm.home.lk233.link:8443
          wait-timeout-minutes: 30
