name: Build Kernel (Reusable)

on:
  workflow_call:
    inputs:
      config_file:
        description: 'Build config file to use'
        required: true
        type: string
      variant_name:
        description: 'Kernel variant name for artifacts'
        required: true
        type: string

env:
  CONTAINER_NAME: sm8650-kernel-builder

jobs:
  build:
    name: Build ${{ inputs.variant_name }}
    runs-on: [home, docker]
    steps:
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ=Etc/UTC
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
          apt-get update && apt-get install -y \
            wget file curl git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
            default-jdk gnupg flex bison gperf build-essential zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
            python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev libtinfo6 \
            make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd --fix-missing
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb
          git config --global --add safe.directory '*'
          git config --global advice.detachedHead false

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup build config
        run: |
          cp ${{ inputs.config_file }} build.config
          echo "[+] Using ${{ inputs.variant_name }} configuration"
          cat build.config

      - name: Prepare kernel source
        run: |
          chmod +x build.sh
          chmod +x scripts/*.sh
          ./build.sh prepare

      - name: Build kernel
        run: |
          ./build.sh kernel

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${{ inputs.variant_name }}-${{ github.sha }}
          path: |
            kernel_source_*/out/**/*.img
            kernel_source_*/out/**/*.zip
          if-no-files-found: warn
          retention-days: 30
